### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by eweren** [solidtime-io/solidtime#113]
Hey there 👋 
Stumbled upon this awesome project. I am wondering if you plan on creating some kind of roadmap or create some issues on what you are planning to create, so that people can contribute too.
Would be awesome to help you with building solidtime.

**Comment by Onatcer** [comment]
Hi, thanks for reaching out, I'm glad you like the project so far! 

We do not currently accept community contributions because the project is still in its early stages, and we are still changing fundamental APIs and how things work under the hood. **We will certainly accept community contributions in the future, but we do not have a definite time frame for that. 

For the roadmap, I'd love to have 1. a better way to show what is planned next and 2. a way to get community feedback on what to prioritize in the development. We were just discussing earlier this week ways to do that, e.g., via feature voting tools or Discord. If anyone has thoughts/suggestions about this (including the tooling, preferably open-source), please feel free to comment below.

**Comment by eweren** [comment]
Makes sense!
I would suggest sticking to Github for a roadmap or feature planning.
There are some good examples on how this could work.

Directus uses Github Projects to communicate it's roadmap and has opened discussion so that people can bring in ideas.

Seems to work very good so far!

**Comment by thelooter** [comment]
Another suggestion would be to move all development and planning to a different Platform like Gitlab. Gitlab offers equally as good if not better Project Management and Planning functionality and doesn't use Code from the Platform to train AI Models. It also offers a far more Mature and integrated CI System and several other features. It is also open source.

https://nogithub.codeberg.page/

If you don't want to move Platforms, which is totally understandable, please ignore this comment

**Comment by korridor** [comment]
Small news on the contributing topic: We now allow contributions to [documentation of solidtime](https://github.com/solidtime-io/docs) for example for self-hosting guides for other platforms, or more detailed information.
