### ISSUE TITLE
Profile picture doesn't seem to be stored after upload

### ISSUE THREAD

**Issue by maxheadroom** [solidtime-io/solidtime#168]
I'm running a self-hosted setup of solid time following your instructions at https://github.com/solidtime-io/self-hosting-examples/tree/main/0-docker-traefik-with-database

Everything seems to be running fine so far. I tried to upload an avatar picture for my profile (an PNG file). But looks like that got not persisted properly. I'm getting a broken image shown and see in the browser console that the respective picture results in a 404 HTTP error. 

I've checked the logs but don't find any hints at what might be going wrong here.

**Comment by korridor** [comment]
Thanks for your issue @maxheadroom!

I think this is the same problem as this issue #128 and since we have not had an official release since then, it was a bit premature of me to close the issue.

Please try to run `php artisan storage:link` and see if it works then. If it works, it is the same issue and I'll write if there is a new release that runs the command automatically on startup.

**Comment by korridor** [comment]
This should be fixed with the release of [v0.2.0](https://github.com/solidtime-io/solidtime/releases/tag/v0.2.0)
