### ISSUE TITLE
Incorrect documentation: .env file is not referenced in docker-compose.yml

### ISSUE THREAD

**Issue by MK1Roxxor** [solidtime-io/solidtime#171]
The documentation refers to a .env file, that file is never used in the docker-compose.yml. Only laravel.env is used, .env is completely unused, yet still mentioned in the documentation. Either I am missing something, or the documentation is incorrect and should be fixed.

**Comment by korridor** [comment]
The `.env` is automatically used by `docker compose`. (Docker docs: https://docs.docker.com/compose/environment-variables/variable-interpolation/) That is also the reason we have two env files, since we want the configuration of the `docker-compose.yml` file to be separate from the application's env file.
