### ISSUE TITLE
Add change language on the import instructions for Clockify

### ISSUE THREAD

**Issue by Zarpyk** [solidtime-io/solidtime#294]
Clockify export the data with the language that the user have selected, for example if I have Spanish, the csv is exported with spanish.

![imagen](https://github.com/user-attachments/assets/73991036-6632-4fc3-9961-2c906409e1f0)

**Comment by korridor** [comment]
@Zarpyk Thank you for the report! I was not aware that Clockify operates like that. They really make writing an importer a challenge ;)

Would it be possible for you to change the language to English just for the import and change it back afterwards? I can add this to the instructions. Because I'm not sure how feasible it is to support all languages that Clockify supports, but we'll look into that.

**Comment by Zarpyk** [comment]
> @Zarpyk Is the CSV export of Clockify also in Spanish if you export projects?

Yes, it also export with Spanish.

**Comment by korridor** [comment]
I just updated the description of the imports. Commit: https://github.com/solidtime-io/solidtime/pull/301/commits/ccc07c423537c58cb15f5dbb47e1290f5e500697
